artifacts_root: artifacts  #it will generate artifacts folder
#first create data_ingestion config

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sheriff786/new_branch_repository/raw/main/samsumdata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]
  